### ISSUE TITLE
Something to make it better;

### ISSUE THREAD

**Issue by sinanislekdemir** [Coder-X15/CmdPrime#1]
Hi Sam,

I was on vacation and just had a chance to see your code. Good stuff. Tho, as a Python coder, just to encourage you to write cleaner code, I'd like to make some proposals;

You should use a code formatter. Official code formatter for Python is Black. 
https://github.com/psf/black

Also a linter like flake8. It will point out that your lambda definition is better to be replaced with a def.

So, after those tooling suggestions, here are my proposals;

1. You should guard your input against invalid values and show meaningful messages to user.
```python
import sys

if len(sys.argv) < 2:
    print("Not enough parameters, range is missing")
    exit(1)

if len(sys.argv) > 2:
    print("Too many parameters.")
    exit(2)

input_range = sys.argv[1]
if not input_range.isnumeric():
    print("Range must be a number")
    exit(3)

input_range_integer = int(input_range)
```

2. You should name your variables in a bit more self explaining way;
```python
series_a = [2, 5]
series_b = [3, 7]

for i in range(input_range_integer):
    series_a.append(series_a[1] + (i + 1) * 6)
    series_b.append(series_b[1] + (i + 1) * 6)

combined_series = list(set(series_a).union(set(series_b)))
combined_series.sort()

```

3. Definition of "Range" is ambiguous. Generally the user experience for prime number ranges is "find prime numbers from 0 to 1000". So the range is 1000. This doesn't mean to find 1000 prime numbers. This means to find prime numbers upto given range. 

4. Use logging for irrelevant information;
```python
import logging

logger = logging.getLogger(__name__)
logger.setLevel(logging.WARNING)

c_handler = logging.StreamHandler()
logger.addHandler(c_handler)

....
logger.info(("For n = {0} , removed : {1}".format(n, removed)))
```
so If I want to see the info stuff, I can change the log level from `logging.WARNING` to `logging.DEBUG`

5. Use a better output format; instead of a `print(c)`, a simple change like `print(','.join([str(item) for item in combined_series]))` would highly benefit as I can use the output in bash like:

```
python CmdPrime.py 100 | tr ',' "\n" | wc -l 
```

so it would give me number of items found.

Also, your code finds 111 prime numbers for range 100.

**Comment by sinanislekdemir** [comment]
Also in addition to those, I now realized that your way is too slow; here is a comparison:

```
It took 5.332900762557983 seconds for Sam
It took 0.0022211074829101562 seconds for Sinan
```

And the code:
```python
t1 = time.time()
input_range_integer = int(input_range)

series_a = [2, 5]
series_b = [3, 7]

for i in range(input_range_integer):
    series_a.append(series_a[1] + (i + 1) * 6)
    series_b.append(series_b[1] + (i + 1) * 6)

combined_series = list(set(series_a).union(set(series_b)))
combined_series.sort()


expr = lambda n, x: n ** 2 + 2 * x * n
for n in combined_series:
    removed = {}
    for j in range(input_range_integer):
        if expr(n, j) in combined_series and expr(n, j) <= max(combined_series):
            combined_series.remove(expr(n, j))

    logger.info(("For n = {0} , removed : {1}".format(n, removed)))

diff = time.time() - t1
print(f"It took {diff} seconds for Sam")
t1 = time.time()
primes = [prime for prime in range(max(combined_series)) if is_prime(prime)]

diff = time.time() - t1
print(f"It took {diff} seconds for Sinan")
```

and `is_prime` function that I've used:
```python
def is_prime(n):
    if n == 2 or n == 3:
        return True
    if n < 2 or n % 2 == 0:
        return False
    if n < 9:
        return True
    if n % 3 == 0:
        return False
    r = int(n ** 0.5)
    # since all primes > 3 are of the form 6n ± 1
    # start with f=5 (which is prime)
    # and test f, f+2 for being prime
    # then loop by 6.
    f = 5
    while f <= r:
        if n % f == 0:
            return False
        if n % (f + 2) == 0:
            return False
        f += 6
    return True
```

**Comment by Coder-X15** [comment]
Great , sir ! I knew mine was a really weak guy..... but never mind. I know nothing of those code formatters, but yes I'll work upon your suggestions. They're pretty good !

Btw, how was your vacation ? Here in India, Corona is strengthening its grip someway and I am having online classes (2 subjects a day). 

I don't know if this kind of informal talk is accepted, but still I felt like talking.. 😄

Thanks !

**Comment by Coder-X15** [comment]
After all, do all issues end here ? Is it time to close this issue ?

**Comment by sinanislekdemir** [comment]
Yep, I am now closing the issue :) the rest is off-topic. 
Input validations are a bug that you should work on. Also I suggest you to take a look at these topics:

- List comprehensions 
- Dict comprehensions

(Those are faster than regular loops)

Your mathematical approach is correct, can't argue on that. It is just the way you implement it to Python code. :)

**Comment by Coder-X15** [comment]
You are really GR8 ! (I use GR8 for 'Great !')

**Comment by Coder-X15** [comment]
I am currently editing the code as you said. Thanks for your reviews.....

**Comment by Coder-X15** [comment]
I edited it. Please try and let me know if that would suffice.

**Comment by Coder-X15** [comment]
🙂🙂

**Comment by Coder-X15** [comment]
What I did is that I copied the debugged code you put in here and placed it in the place of my original code ( I have to shut down the computer by 1:00 pm IST  to get back to studies, so I shouldn't spend time on fully going through the code and editing it). I believe that your edits will work..

**Comment by Coder-X15** [comment]
The thing worked, but I wasn't able to see anything in the 'removed' dictionary. Why ? Any way I can do away with this ?

**Comment by Coder-X15** [comment]
I have no knowledge of iOS and MacOS related stuff.....😅

**Comment by Coder-X15** [comment]
Maybe I'll be able to see your suggestions tomorrow....

**Comment by sinanislekdemir** [comment]
> The thing worked, but I wasn't able to see anything in the 'removed' dictionary. Why ? Any way I can do away with this ?

I didn't get this one? I guess you mean by the logs? 
To see the logs, you should change the logging level;
from:

```python
logger.setLevel(logging.WARNING)
```

to 

```python
logger.setLevel(logging.DEBUG)
```

**Comment by Coder-X15** [comment]
Not really.... I meant that during the filtering process, a dictionary called 'removed' is displayed on the screen to show those numbers that are removed during the process......... No problem. I have resolved the issue. Just missed a line in the code. That's all. Btw, the tool is ready for use !

**Comment by Coder-X15** [comment]
Ok... added some comments (they are inevitable, right ?) to the program for others to understand. Hope you'll enjoy this !
